### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by HuangJiaLian** [ipapi-co/weather-from-ip-address#1]
```python

In [1]: from requests import get
   ...:
   ...: ip = '208.67.222.222'
   ...:
   ...: latlong = get('https://ipapi.co/{}/latlong/'.format(ip)).text.split(',')
   ...:
   ...: weather = get('http://api.openweathermap.org/data/2.5/weather?lat={}&lon={
   ...: }&appid=API_KEY'.format(latlong[0], latlong[1])).json()

In [2]: weather
Out[2]:
{'cod': 401,
 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
```

**Comment by ipapi-co** [comment]
@HuangJiaLian This error is unrelated to our API. To use this integration, you would need 2 services : 

1. Our service to fetch the zip code for an IP address 
2. A service that provides details of the weather for a zip code. 

The error pertains to (2)

**Comment by ipapi-co** [comment]
@HuangJiaLian This error is unrelated to our API. To use this integration, you would need 2 services :

1. Our service to fetch the location for an IP address
2. A service that provides details of the weather given the location

The error pertains to (2)

**Comment by ipapi-co** [comment]
If you notice any issue with our service, please don't hesitate to reach out to us.
